export const getCharacters = [{"Id":1,
                        "Name":"Myrcella Baratheon",
                        "IsFemale":true,
                        "Culture":"",
                        "Titles":["Princess"],
                        "Aliases":[],
                        "Born":"In 290 AC, at King's Landing",
                        "Died":"","Father":null,
                        "Mother":null,
                        "Spouse":null,
                        "Children":[],
                        "Allegiances":[16],
                        "Books":[1,2,3,5,8],
                        "PovBooks":[],
                        "PlayedBy":["Aimee Richardson, Nell Tiger Free"],
                        "TvSeries":["Season 1","Season 2","Season 5", "Season 6"],
                        "pawn": "/images/1x/baratheon_pawn.png",
                        "image":['/images/1x/myrcella_baratheon.png']},
                        
                        
                        {"Id":1,
                        "Name":"Ormund Baratheon",
                        "IsFemale":false,
                        "Culture":"",
                        "Titles":["Lord Paramount of the Stormlands","Lord of Storm's End","Hand of the King"],
                        "Aliases":[],"Born":"",
                        "Died":"In 260 AC, at Stepstones",
                        "Father":null,
                        "Mother":null,
                        "Spouse":870,
                        "Children":[],
                        "Allegiances":[17],"Books":[11],
                        "PovBooks":[],
                        "PlayedBy":[""],
                        "TvSeries":[],
                        "pawn": "/images/1x/baratheon_pawn.png",
                        "image":['/images/1x/ormund_baretheon.png']},
                        
                        {"Id":2,
                        "Name":"Rhaenys Targaryen",
                        "IsFemale":true,
                        "Culture":"Valyrian",
                        "Titles":["Princess"],
                        "Aliases":["The Queen Who Never Was"],
                        "Born":"In 74 AC",
                        "Died":"In 129 AC, at Rook's Rest",
                        "Father":null,
                        "Mother":null,
                        "Spouse":253,
                        "Children":[],
                        "Allegiances":[378,407],
                        "Books":[11,10,9],
                        "PovBooks":[],
                        "PlayedBy":[""],
                        "TvSeries":[],
                        "pawn": "/images/1x/targeryan_pawn.png",
                        "image":['/images/1x/daenerys_targeryan.png']},

                        {"Id":2,
                        "Name":"Daenerys Targaryen",
                        "IsFemale":true,
                        "Culture":"Valyrian",
                        "Titles":["Queen of the Andals and the Rhoynar and the First Men, Lord of the Seven Kingdoms","Khaleesi of the Great Grass Sea","Breaker of Shackles/Chains","Queen of Meereen","Princess of Dragonstone"],
                        "Aliases":["Dany","Daenerys Stormborn","The Unburnt","Mother of Dragons","Mother","Mhysa","The Silver Queen","Silver Lady","Dragonmother","The Dragon Queen","The Mad King's daughter"],
                        "Born":"In 284 AC, at Dragonstone",
                        "Died":"",
                        "Father":null,
                        "Mother":null,
                        "Spouse":1346,
                        "Children":[],
                        "Allegiances":[378],
                        "Books":[5],
                        "PovBooks":[1,2,3,8],
                        "PlayedBy":["Emilia Clarke"],
                        "TvSeries":["Season 1","Season 2","Season 3","Season 4","Season 5", "Season 6"],
                        "pawn": "/images/1x/targeryan_pawn.png",
                        "image":['/images/1x/daenerys_targeryan_2.png']},

                        {"Id":3,
                        "Name":"Theon Greyjoy",
                        "IsFemale":false,
                        "Culture":"Ironborn",
                        "Titles":["Prince of Winterfell","Captain of Sea Bitch","Lord of the Iron Islands (by law of the green lands)"],
                        "Aliases":["Prince of Fools","Theon Turncloak","Reek","Theon Kinslayer"],
                        "Born":"In 278 AC or 279 AC, at Pyke",
                        "Died":"",
                        "Father":null,
                        "Mother":null,
                        "Spouse":null,
                        "Children":[],
                        "Allegiances":[169],
                        "Books":[1,3,5],
                        "PovBooks":[2,8],
                        "PlayedBy":["Alfie Allen"],
                        "TvSeries":["Season 1","Season 2","Season 3","Season 4","Season 5", "Season 6"],
                        "pawn": "/images/1x/greyjoy_pawn.png",
                        "image":['/images/1x/theon_greyjoy.png']},


                        {"Id":3,
                        "Name":"Euron Greyjoy",
                        "IsFemale":false,
                        "Culture":"Ironborn",
                        "Titles":["Iron King","King of the Isles and the North  King of Salt and Rock","Son of the Sea Wind","Lord Reaper of Pyke","Captain of the Silence"],
                        "Aliases":["Crow's Eye","Euron Crow's Eye"],
                        "Born":"or before 267 AC","Died":"",
                        "Father":836,
                        "Mother":null,
                        "Spouse":null,
                        "Children":[],
                        "Allegiances":[],
                        "Books":[1,2,3,5,8],
                        "PovBooks":[],
                        "PlayedBy":[""],
                        "TvSeries":[],
                        "pawn": "/images/1x/greyjoy_pawn.png",
                        "image":['/images/1x/euron_greyjoy.png']},

                        {"Id":4,
                        "Name":"Alys Arryn",
                        "IsFemale":true,
                        "Culture":"",
                        "Titles":[],
                        "Aliases":[],
                        "Born":"",
                        "Died":"",
                        "Father":null,
                        "Mother":null,
                        "Spouse":868,
                        "Children":[],
                        "Allegiances":[7,378],
                        "Books":[11],
                        "PovBooks":[],
                        "PlayedBy":[""],
                        "TvSeries":[],
                        "pawn": "/images/1x/arryn_pawn.png",
                        "image":['/images/1x/alys_arryn.png']},
                      

                        {"Id":4,
                        "Name":"Artys I Arryn",
                        "IsFemale":false,
                        "Culture":"Andal",
                        "Titles":["King of Mountain and Vale","Ser"],
                        "Aliases":["Falcon Knight","Winged Knight"],
                        "Born":", at Giant's Lance",
                        "Died":"",
                        "Father":null,
                        "Mother":null,
                        "Spouse":null,
                        "Children":[],
                        "Allegiances":[],
                        "Books":[11],
                        "PovBooks":[],
                        "PlayedBy":[""],
                        "TvSeries":[],
                        "pawn": "/images/1x/arryn_pawn.png",                        
                        "image":['/images/1x/Robin_arryn.png']},
                       

                        {"Id":5,
                        "Name":"Jaime Lannister",
                        "IsFemale":false,
                        "Culture":"Westerlands",
                        "Titles":["Ser","Lord Commander of the Kingsguard","Warden of the East (formerly)"],
                        "Aliases":["The Kingslayer","The Lion of Lannister","The Young Lion","Cripple"],
                        "Born":"In 266 AC, at Casterly Rock",
                        "Died":"",
                        "Father":null,
                        "Mother":null,
                        "Spouse":null,
                        "Children":[],
                        "Allegiances":[229],
                        "Books":[1,2],
                        "PovBooks":[3,5,8],
                        "PlayedBy":["Nikolaj Coster-Waldau"],
                        "TvSeries":["Season 1","Season 2","Season 3","Season 4","Season 5"],
                        "pawn": "/images/1x/lannister_pawn.png",
                        "image":['/images/1x/jamie_lannister.png']},
                        

                        {"Id":5,
                        "Name":"Tyrion Lannister",
                        "IsFemale":false,
                        "Culture":"",
                        "Titles":["Acting Hand of the King (former)","Master of Coin (former)"],
                        "Aliases":["The Imp","Halfman","The boyman","Giant of Lannister","Lord Tywin's Doom","Lord Tywin's Bane","Yollo","Hugor Hill","No-Nose","Freak","Dwarf"],
                        "Born":"In 273 AC, at Casterly Rock",
                        "Died":"",
                        "Father":null,
                        "Mother":null,
                        "Spouse":2044,
                        "Children":[],
                        "Allegiances":[229],
                        "Books":[5,11],
                        "PovBooks":[1,2,3,8],
                        "PlayedBy":["Peter Dinklage"],
                        "TvSeries":["Season 1","Season 2","Season 3","Season 4","Season 5", "Season 6"],
                        "pawn": "/images/1x/lannister_pawn.png",
                        "image":['/images/1x/tyrion_lannister.png']},
        ]


